### ISSUE TITLE
Oracle DB | 스키마 & PL(프로시저 언어) 구현

### ISSUE THREAD

**Issue by hogi2020** [hogi2020/GroupChat_Project#10]

**Comment by hogi2020** [comment]
지선님, ERD 파일 확인했습니다.

[리뷰]
1. mem_talk 테이블이 생성된 이유가 있을까요? (혹시 없어도 되지않을까해서요.) 
2. 단체방 테이블 명을 아래와 같이 명시적으로 바꾸면 좋을 것 같습니다.

talk  -->  talk_room
talk_num  -->  talk_room_id
talk_name  -->  talk_room_name

mem_msg_num  -->  msg_id
date_and_time  -->  date_time

![Image](https://github.com/user-attachments/assets/115b79e6-99b0-455e-91a6-0712e3e62266)

**Comment by Jiseon-0** [comment]
1. mem_talk 테이블이 생성된 이유가 있을까요? 
단톡방 번호와 멤버 아이피를 비교해서 어느 방에 어느 멤버가 말하고 있는지 저장해야해서 생성했습니다.
2. 단체방 테이블 명을 아래와 같이 명시적으로 바꾸면 좋을 것 같습니다.
말씀해주신 이름으로 수정했습니다.
