### ISSUE TITLE
Oracle DB | DB-Server Connection 클래스 생성

### ISSUE THREAD

**Issue by Jiseon-0** [hogi2020/GroupChat_Project#8]

**Comment by hogi2020** [comment]
지선님, ERD 파일 확인했습니다.

[리뷰]
1. mem_talk 테이블이 생성된 이유가 있을까요? (혹시 없어도 되지않을까해서요.) 
2. 단체방 테이블 명을 아래와 같이 명시적으로 바꾸면 좋을 것 같습니다.

talk  -->  talk_room
talk_num  -->  talk_room_id
talk_name  -->  talk_room_name

mem_msg_num  -->  msg_id
date_and_time  -->  date_time

![Image](https://github.com/user-attachments/assets/115b79e6-99b0-455e-91a6-0712e3e62266)

**Comment by Jiseon-0** [comment]
1. 오라클에서 테이블 제대로 뜨는지 확인하기
2. 자바에서 오라클 데이터베이스 가져올 수 있는 DBConnection 파일 생성하기
* 시간적 여유가 된다면 자바와 오라클 연동하는 방법까지 고민해보기

**Comment by hogi2020** [comment]
DB Connection 클래스 및 Dao 파일 구현
